### ISSUE TITLE
TagHelper model 

### ISSUE THREAD

**Issue by ASKemp** [fingers10/JqueryDataTablesServerSide#11]
Hi, thanks again for this.
With regards specifying the model to be passed to the TagHelper, can I specify a model directly or must I only use the model specified for the page, i.e. @Model?
E.g can I specify model="MyDataViewModel" ?

Many thanks.

**Comment by fingers10** [comment]
Hi ASKemp,

You need to pass a object instance. You can try passing `new MyDataViewModel()`. That should work.

Cheers,
Abdul Rahman

**Comment by ASKemp** [comment]
Many thanks indeed
