### ISSUE TITLE
Supply stored procedure for recordset?

### ISSUE THREAD

**Issue by ASKemp** [fingers10/JqueryDataTablesServerSide#13]
Is there any way an existing stored procedure could be supplied as the record set (assuming it support the required parameters for paging etc.)?

My table output brings together data from many table joins and so would benefit from server paging but can't see how I would apply your code to my existing sproc.

**Comment by fingers10** [comment]
Hi ASKemp,

Since your using a procedure, filtering and ordering cannot be done dynamically at the database level by this package. So with your case you can do these on the server(code) level. If you can get the record set as `IEnumerable` or `IQueryable` then you process like how I have implemented in the docs/demo. Hope this helps.

Cheers,
Abdul

**Comment by ASKemp** [comment]
Alternatively, if I use EF Core/Linq etc. to build the query dynamically, how would I go about getting back details across more than one entity?

I.e. you use automapper to map the view model Data against the entity DataEntity. How would I map a projection against a dataset that pulls from more than one entity? Can I do this?

E.g. in your example, if you had a relationship between DataEntity and another entity, say DataEntity2 via a navigation property for something like a country lookup, what would you need to do to pull back the data from both into the table?

Many thanks again.

**Comment by fingers10** [comment]
Hi ASKemp,

This is an open issue I'm working on to enable searching/sorting with relationship models. I'll push this in next release.

But if you're not going to do filtering/ordering on relationship properties, they you can use my package to process and for mapping you can easily get samples using automapper in the internet.

Cheers,
Abdul
