### ISSUE TITLE
[Sortable(Default = true)] don't seam to work.

### ISSUE THREAD

**Issue by ElChepos** [fingers10/JqueryDataTablesServerSide#14]
Hi,

i'm trying to set the default sortable column with the tag 
[Sortable(Default = true)] but it don't seam to do anything. I downloaded the demo project and it don't seam to work.

Is [Sortable(Default = true)] attribute design to replace the order element ?
$('#example').DataTable( {
        "order": [[ 3, "desc" ]]
    } );

Thx

**Comment by fingers10** [comment]
did you try to remove the `"order": [[ 3, "desc" ]]` from your script and checked?

**Comment by ElChepos** [comment]
Hi,

thanks for the fast answer. Yup I do not use the "order": [[ 3, "desc" ]]", I mention it just to be sure the attribute [Sortable(Default = true)] was to replace it.

In fact, I downloaded your demo project, run it without modifying anything and it don't seam to work.

In your demo class you have 
[SearchableString]
[Sortable(Default = true)]
 public string Name { get; set; }

but when the application run the column is not sorted.

**Comment by fingers10** [comment]
I checked the demo project. It should work and its working. By default the results from database will be sorted in ascending order because of `[Sortable(Default = true)]` and the results are sorted. The results will be filtered only if you enter a search term and search.

**Comment by ElChepos** [comment]
When we start the application the first time, the results appears to be sorted, but in reality it because the data in seedData.cs is inserted in order already. But when we check the arrow that display the sorting none is selected. Please refer this screenshot. What I did is move a new DemoEntity with name starting with a B up in the SeedData.cs
https://ibb.co/hF3svXq
But when we press manually the arrow the sort work and the arrow is now selected. Please refer to this screenshot.
https://ibb.co/5krPzZ3

Thx

**Comment by fingers10** [comment]
Interesting. Thanks for figuring out. `[Sortable(Default = true)]` is not a replacement for `order: [[1, "asc"]],` 

`[Sortable(Default = true)]` is added to provider default sort but in this case the DataTables initial request overrides the name with Id.

If you look closely at the ajax request made by DataTables for the first time it passes Id column as default hence its not working. 

![image](https://user-images.githubusercontent.com/43729469/63439772-4d014c00-c44c-11e9-80a7-6ed63fd60342.png)

If you add `order: [[1, "asc"]],` to initialization script, then Jquery DataTables passes Name column for default sort and results are sorted and indicated by sort indicators.

Thanks,
Abdul

**Comment by ElChepos** [comment]
Is that consider a bug ? Because in that case [Sortable(Default = true)] is not really useful right ?

I use the jquery datatable in a generic view so it not really an option to put the order: [[1, "asc"]] since I don't know which column to order by in that view. Hence the use of [Sortable(Default = true)]

Again thank you for your fast support !

**Comment by fingers10** [comment]
Yeah your welcome. This is not a bug. `[Sortable(Default = true)]` works but datatables ajax request overrides this.

In that case may be you can replace `[Sortable(Default = true)]` with `[Sortable]` and jquery datatables will by default pass your table's first column for sorting in asc direction.

This infact needs to be decided by jquery datatables client side configuration and my package is used to process what ever settings that is passed.
