### ISSUE TITLE
Search Input boxes not dynamically created on V2.2.0

### ISSUE THREAD

**Issue by MLohrentz** [fingers10/JqueryDataTablesServerSide#15]
Thanks for an amazing piece of genius code. Not sure if anyone else is experiencing the following issue:

After updating from V2.1.0 to V2.2.0 the search input boxes are no longer created dynamically after the table is initiated.

**Comment by fingers10** [comment]
Can you check your tag helper With the demo project? 

Here you go,
```cshmtl
<jquery-datatables id="fingers10"
              class="table table-sm table-dark table-bordered table-hover"
              model="@Model"
              thead-class="text-center"
              enable-searching="true"
              search-row-th-class="p-0"
              search-input-class="form-control form-control-sm"
              search-input-style=""
              search-input-placeholder-prefix="Search">
</jquery-datatables>
```

**Comment by MLohrentz** [comment]
Thanks for the quick response Abdul.

Unfortunately something still not working for me. Not a big deal at the moment. I am actually extremely happy to stick to v2.1.0.

There are a few other issues I have detected with the searching when certain datatable options are enabled such as:
- ScrollX
- ScrollY
- responsive: true

Overall this is an excellent package as it solves huge performance issues I have been experiencing throughout my projects. So thanks a million.

**Comment by fingers10** [comment]
Hey @MLohrentz,

Thanks for the kind words. I tested well before releasing. Right now v2.1.0 works for you. But I want to know what made v2.2.0 to not work for you. If this is due to issue in my package, I'll definitely fix and add to patch release.

Please can you share your client side jquery datatables initialization script? I'll try to mock the your configuration and see where the issue is.

Meanwhile did you compared your `jquery-datatables` tag helper with the above one?

Cheers,
Abdul Rahman

**Comment by MLohrentz** [comment]
Hey Abdul

Thanks. Yes of course I can. I have compared the tag helper already, I have used yours exactly as provided. 

I have also tried to include your package on a clean sample project as well to eliminate anything unrelated to the package being the cause...with no luck. Which is the only reason i listed this as an issue. Although I would be extremely embarrassed if the cause is my jquery... I would be more than happy to share lol. Im providing my model below as well

`"use strict";
$(() => {
    if ($('#ExcelStyle').length !== 0) {
        var table = $('#ExcelStyle').DataTable({
            language: {
                "processing": '<div id="pageLoadingDatatables"><div class="circle"></div><div class="circle1"></div><div class="circle2"></div><div class="circle3"></div><div class="loading"><span class="loading0">loading</span></div></div>',
                "zeroRecords": "No matching records found",
                "search": "Filter records: ",
                "lengthMenu": "<div class='d-inline'>Show: </div> _MENU_"
            },
            scrollCollapse: true,
            processing: true,
            serverSide: true,
            orderCellsTop: true,
            autoWidth: false,
            deferRender: true,
            "lengthMenu": [
                [20, 30, 100, 250, 500],
                [20, 30, 100, 250, 500]
            ],
            "dom": '<"row"<"col-lg-6 col-12"Bl> <"col-lg-6 col-12 text-right">><"row"<"col-12"t>><"row"<"col-lg-6 col-12"i> <"col-lg-6 col-12"p>><"clear">',
            "order": [
                [7, "asc"]
            ],
            buttons: [{
                text: 'Export to Excel',
                className: 'btn btn-sm btn-dark',
                action: function(e, dt, node, config) {
                    window.location.href = "/Users/GetExcel";
                },
                init: function(api, node, config) {
                    $(node).removeClass('dt-button');
                }
            }],
            ajax: {
                type: "POST",
                url: '/Vouchers/LoadVoucherTable/',
                contentType: "application/json; charset=utf-8",
                async: true,
                headers: {
                    "XSRF-TOKEN": document.querySelector('[name="__RequestVerificationToken"]').value
                },
                data: function(data) {
                    let additionalValues = [];
                    additionalValues[0] = "Take1";
                    additionalValues[1] = "Take2";
                    data.AdditionalValues = additionalValues;
                    return JSON.stringify(data);
                }
            },
            // the order of ApplicationUserMap, ApplicationUser and the actual view datatables output Javascript has to match display order!!
            columns: [{
                data: "Id",
                visible: false,
                searchable: false
            }, {
                data: "VoucherId",
                visible: false,
                searchable: false
            }, {
                data: "Voucher",
                visible: false,
                searchable: false
            }, {
                data: "UniqueCode",
                name: "co", //eq gt
                searchable: true
            }, {
                data: "ValidStart",
                name: "co",
                title: "Valid From",
                searchable: true,
                render: function(data, type, row) {
                    return moment(row["ValidStart"]).format('DD / MMM / YYYY hh:mm A')
                },
            }, {
                data: "ValidEnd",
                name: "co", //eq gt
                title: "Expires",
                searchable: true,
                render: function(data, type, row) {
                    return moment(row["ValidEnd"]).format('DD / MMM / YYYY hh:mm A')
                },
            }, {
                data: "VoucherLogs",
                visible: false,
                searchable: false
            }, {
                data: "ApplicationUserId",
                visible: false,
                searchable: false
            }, {
                data: "ApplicationUser",
                name: "co", //eq gt,
                title: "Redeemed By",
                searchable: true,
                render: function(data, type, row) {

                    var ReturnUserString = '';

                    if (row["ApplicationUser"] !== 'undefined' && row["ApplicationUser"] !== null) {

                        ReturnString = row["ApplicationUser"]["Title"] + ' ' + row["ApplicationUser"]["FirstName"] + ' ' + row["ApplicationUser"]["LastName"];
                    } else {
                        ReturnString = ' ';
                    }

                    return ReturnString;
                },
            }, {
                data: "GiftVoucher",
                visible: false,
                searchable: false
            }, {
                data: "InitialVoucherValue",
                name: "co", //eq gt
                title: 'Value',
                searchable: true,
                className: "text-right",
                render: function(data, type, row) {
                    return 'R ' + row["InitialVoucherValue"].toFixed(2)
                }
            }, {
                data: "VoucherValue",
                name: "co",
                title: "Remaining Balance",
                searchable: true,
                className: "text-right",
                render: function(data, type, row) {
                    return 'R ' + row["VoucherValue"].toFixed(2)
                }
            }, {
                data: "GiftUser",
                visible: true,
                title: "Actions",
                className: "text-center noPadding gridViewIcons",
                render: function(data, type, row) {

                    var ReturnString = '<div class="row">';

                    if (row["GiftUser"]["ApplicationUserId"] !== 'undefined' && row["GiftUser"]["ApplicationUserId"] !== null) {
                        ReturnString = ReturnString + '<div class="col p-0"><a class="gridViewLinks HoverGold fancyBoxLarge" data-fancybox data-type="iframe" href="/Home/UserRecord/' + row["GiftUser"]["ApplicationUserId"] + '" data-src="/Home/UserRecord/' + row["GiftUser"]["ApplicationUserId"] + '" data-toggle="tooltip" data-placement="left" title="View Purchaser Record"><i class="mdi mdi-account-card-details-outline"></i></a></div>';
                    } else {
                        ReturnString = ReturnString + '<div class="col p-0"><a class="gridViewLinks HoverGold disabled" disabled href="#" data-toggle="tooltip" data-placement="left" title="View Purchaser Record"><i class="mdi mdi-account-card-details-outline"></i></a></div>';
                    }

                    if (row["ApplicationUser"] !== 'undefined' && row["ApplicationUser"] !== null) {
                        ReturnString = ReturnString + '<div class="col p-0"><a class="gridViewLinks HoverGold fancyBoxLarge" data-fancybox data-type="iframe" href="/Home/UserRecord/' + row["ApplicationUser"]["Id"] + '" data-src="/Home/UserRecord/' + row["ApplicationUser"]["Id"] + '" data-toggle="tooltip" data-placement="left" title="View Redeemer Record"><i class="mdi mdi-account-card-details"></i></a></div>';
                    } else {
                        ReturnString = ReturnString + '<div class="col p-0"><a class="gridViewLinks HoverGold disabled" disabled href="#" data-toggle="tooltip" data-placement="left" title="View Redeemer Record"><i class="mdi mdi-account-card-details"></i></a></div>';
                    }
                    ReturnString = ReturnString + '</div>';
                    return ReturnString;
                }
            }, ],
            "drawCallback": function(settings) {
                $('[data-toggle="tooltip"]').tooltip({
                    placement: 'top',
                    trigger: 'hover',
                    container: 'body'
                });
                $(".reloadParentOnClose").fancybox({
                    fullScreen: {
                        autoStart: false
                    },
                    iframe: {
                        css: {
                            width: '60%'
                        }
                    },
                    clickSlide: 'false',
                    clickOutside: 'false',
                    loop: true,
                    buttons: [
                        'close'
                    ],
                    thumbs: {
                        autoStart: false,
                        hideOnClose: false,
                        parentEl: '.fancybox-container',
                        axis: 'y'
                    },
                    touch: {
                        vertical: false, // Allow to drag content vertically
                        momentum: false // Continue movement after releasing mouse/touch when panning
                    },
                    afterClose: function() {
                        parent.$("#pageLoadingFull").show();
                        parent.location.reload(true);
                    }
                });

                $('#ExcelStyle thead input').each(function() {
                    $(this).attr("placeholder", "Search...");
                });


            }
        });

        table.columns().every(function(index) {
            $('#ExcelStyle thead tr:last th:eq(' + index + ') input').on('keyup change input', function(e) {

                //if (e.keyCode === 13) {
                if ($(this).val().length > 1 || $(this).val().length < 1 || !this.value) {
                    table.column($(this).parent().index() + ':visible').search(this.value).draw();
                }
                //}
            });
        });

        $(".dataTables_length select").addClass("form-control");
    }
});`

My Model:

`public class VoucherInstanceMap
{
    public VoucherInstanceMap() : base() { }

    [SearchableString]
    [Sortable]
    public int Id { get; set; }

    [SearchableString]
    [Sortable]
    public int? VoucherId { get; set; }
	
    [SearchableString]
    [Sortable]
    public Voucher Voucher { get; set; }

    [SearchableString]
    [Sortable]
    public string UniqueCode { get; set; }

    [SearchableString]
    [Sortable]
    public decimal InitialVoucherValue { get; set; }

    [SearchableString]
    [Sortable]
    public decimal VoucherValue { get; set; }

    [SearchableString]
    [Sortable]
    public DateTime? ValidStart { get; set; }

    [SearchableString]
    [Sortable]
    public DateTime? ValidEnd { get; set; }

    public ICollection<VoucherLog> VoucherLogs { get; set; }

    [SearchableString]
    [Sortable]
    public string ApplicationUserId { get; set; }
	
	[SearchableString]
    [Sortable]
    public ApplicationUser ApplicationUser { get; set; }

    [SearchableString]
    [Sortable]
    public GiftUser GiftUser { get; set; }

    [Sortable]
    public bool GiftVoucher { get; set; }
}`

**Comment by MLohrentz** [comment]
Hi Abdul

I have uninstalled the package and reinstalled the package from scratch on a new solution... and everything seems to be working fine. I'm pretty confused at the moment however I can confirm that it's not a 2.2.0 issue...but rather related to my previous solution.

Thanks again for your assistance and apologies for not being able to pin point the exact cause.

**Comment by MLohrentz** [comment]
Hi Abdul

Ok I found the issue for me: Previously, when all worked well (V2.1.0), I was passing my actual model to my view.

It seems you are passing your Demo (Demo.cs) model to your view, and not your actual entity model (DemoEntity.cs) and letting the mapping take care of the rest.

If I add the search and sort properties ([SearchableString][Sortable] etc..) to my actual entity model, the search inputs appears as expected. I have checked my mappings and all seems fine. Can you please confirm if the intention is to pass the mapped model or the actual entity model to the view?

I have to confess I have been slightly out of focus due to other deadlines so I might have missed something and will reflect again on the matter as soon as I get a proper gap.

**Comment by fingers10** [comment]
Well my intention was to pass the view model not the entity model. Your using DDD approach?

**Comment by MLohrentz** [comment]
Nope. Im using MVC. my model is part of a complex view model consisting of many objects. One of which is the model I am trying to display in the datatables.

So i have for example a model passed through to my view consisting of 3 objects and one or those is the actual model used for displaying the datatables. So in my helper tag i am referring to my model as model="@Model.IWantThisModel" instead of only having model="@Model".

This works btw. I have passed the model successfully through an even deeper relationship (@Model.firstModel.secondModel.IWantThisModel).

Ill give it another go and follow up
