### ISSUE TITLE
Support for core 3.0

### ISSUE THREAD

**Issue by manuelv21** [fingers10/JqueryDataTablesServerSide#17]
Hi, are there plans to release an update for core 3.0 ?

Actually show this error on launch:

"Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"

thanks

**Comment by fingers10** [comment]
Yes I'm working on upgrading. I'll release a new version soon.
