### ISSUE TITLE
DataTable capsulation in a class and server-side generation of client-side code based on model/data

### ISSUE THREAD

**Issue by Namoshek** [fingers10/JqueryDataTablesServerSide#2]
Hi Abdul,

thank you for the nice package! I was looking around for quite some time until I stumbled across your quite new project. It seems there are not as many useful and up to date projects concerning DataTables in ASP.NET (Core, MVC, ...) as you'd expect and like.

The part that annoys me the most about the current DataTable packages is that you always have to write the client-side code individually and separately from the server-side code for each table although it would make sense to generate the code based on what is delivered by the server. Meaning it should be possible to generate at least the
```js
columns: [
    {
        title: "Name",
        data: "Name",
        name: "eq",
        sortable: true,
        searchable: true
    },
    {
        title: "Position",
        data: "Position",
        name: "co",
        sortable: true,
        searchable: true
    }
]
```
part of the client-side code based on what is declared on the server-side, saving a lot of time and reducing the risk of introducing errors.

What I've learned from other languages such as PHP, this approach works great and isn't even too hard to implement. In one of my projects, I'm using a package called [`yajra/laravel-datatables`](https://github.com/yajra/laravel-datatables) (plus some extension packages) which provides a way to wrap everything related to a datatable into one class which is then used to display the table, provide table data, filter the data and transform the output if necessary. The code for a basic table looks like this:
```php
<?php

namespace App\DataTables;

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\URL;
use Yajra\DataTables\Services\DataTable;

/**
 * Class UserDataTable
 *
 * @package App\DataTables
 */
class UserDataTable extends DataTable
{
    /**
     * Build DataTable class.
     *
     * @param mixed $query Results from query() method.
     * @return \Yajra\DataTables\DataTableAbstract
     */
    public function dataTable($query)
    {
        return datatables($query)
            ->addColumn('roles', function (User $user) {
                return $user->roles->implode('name', ', ');
            })
            ->editColumn('created_at', function (User $user) {
                return format_date($user->created_at);
            })
            ->addColumn('action', 'users.components.action_column');
    }
    /**
     * Get query source of dataTable.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query()
    {
        return User::with('usergroups');
    }
    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->addAction()
            ->ajax(['type' => 'POST'])
            ->parameters(array_merge(
                $this->getBuilderParameters(),
                [
                    'fixedColumns' => [
                        'leftColumns' => 1,
                        'rightColumns' => 1,
                    ],
                ]
            ));
    }
    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            ['data' => 'id', 'title' => trans('users.table.header.id')],
            ['data' => 'name', 'title' => trans('users.table.header.name')],
            ['data' => 'email', 'title' => trans('users.table.header.email')],
            ['data' => 'roles', 'searchable' => false, 'orderable' => false, 'title' => trans('users.table.header.roles')],
            ['data' => 'created_at', 'title' => trans('users.table.header.created_at')],
        ];
    }
    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return date('Ymd_His') . '_users';
    }
}
```

A little explanation:
- The method `dataTable($query)` takes the results of a query and transforms them. Translated to C#, it means we'd pass something like a list or collection which can be manipulated. Maybe with some nice convenience methods.
- The method `query()` returns the base query which can be manipulated with filtering, sorting, etc. Translated to C#, this would be a LINQ query.
- The method `html()` is used to build the client-side code for the datatable. The builder can have some global defaults and a variety of overrides as you can see.
- The method `getColumns()` returns a list of columns. This one is tricky to explain, because I think we actually don't need it. We could build the same data based on attributes of a view model for example.
- The method `filename()` is only there to provide a way of customizing the file name of exports like XLSX, CSV, ...

In the controller we only have to render the table with `return $dataTable->render('users.list');` which uses a view template called `users.list` where we only have to print the table and the script in the desired location:
```blade
<div class="row">
    <div class="col-md-12">
        <div class="box box-default">
            <div class="box-body">
                {{ $dataTable->table([], true) }}
            </div>
        </div>
    </div>
</div>

@push('scripts')
    {!! $dataTable->scripts() !!}
@endpush
```

I'd like to hear what you think about implementing something similar in ASP.NET. In my opinion, this would be somewhat of a game changer if done properly as it makes building DataTables really a breeze.

**Comment by fingers10** [comment]
Dear Namoshek,

Thanks for reaching out. The feature looks interesting and great. I was also planning to implement something like this in near future.

Right now I'm working to add Excel generation functionality to the project based on the ViewModel. I'll add this to my JqueryDataTablesServerSide todo list. 


Thanks,
Abdul

**Comment by Namoshek** [comment]
I invested some time into this as it is something I really needed to get going and so it comes I just released my own package doing pretty much what I described above: [DataTables.NetStandard](https://github.com/Namoshek/DataTables.NetStandard).

Putting all the things described into your package would have been a bit difficult after thinking some time about it. In the end, the design is quite different in most aspects...

**Comment by fingers10** [comment]
Hi Namoshek,

After analyzing this issue for a very long time, I have decided **not to implement** this. As this will make the scripts to be written in views to work. I personally don't prefer to write scripts in views. This will be not much useful if I need to maintain my scripts in a separate js files. Moreover this **will make my nuget package more complex**. That's not what I want. 

> I just want my package to be a **simple server side processor and not a generator**.

Generating works and other heavy lifting jobs are already done by jquery datatables library on the client side and I think **most developers don't prefer to write jquery datatable instantiation and configuration logic's on the server side**. I bet they prefer client side to do that. And if in case they need this functionality or someone read this issue, 

> I request them to go ahead and use your [DataTables.NetStandard](https://github.com/Namoshek/DataTables.NetStandard) nuget package. 

I think you have spent a lot of time making your own package. I seems to be more complex to me. Anyways **credits to you for developing the huge stuff**. I **appreciate**.

Cheers,
Abdul
