### ISSUE TITLE
SearchOptionsProcessor (Value cannot be null. (Parameter 'itemName'))

### ISSUE THREAD

**Issue by HunainD** [fingers10/JqueryDataTablesServerSide#25]
Hi Abdul Rahman,

I know this problem is not related to your component but i wanted to ask some help from you.
I am using mongo db as a database, everything is going fine but i am not able to run search functionality successfully.
i am having Value cannot be null. (Parameter 'itemName') error. after googling a bit i came across this [link](https://jira.mongodb.org/browse/CSHARP-2422). I provided the name as mentioned in the blog and the error is gone but i am not getting the search functionality properly.
can you please help me regarding problem.

**Comment by HunainD** [comment]
Sorry Abdul Rahman,

I solved it i was just missing a simple thing. i downloaded your code from git hub and copied the SearchOptionsProcessor to my project and modified line number 90 to var obj = Expression.Parameter(typeof(TEntity), "search"); //ExpressionHelper.Parameter<TEntity>(); and it worked. if it is correct can you please update your code and also the nuget package so that i can continue using the component' s class rather than mine.

**Comment by fingers10** [comment]
looks like this is a issue with mongo db c# driver. did you report this to them? whats their response for this?
