### ISSUE TITLE
Advanced Search in Datatable

### ISSUE THREAD

**Issue by BernardBoakye** [fingers10/JqueryDataTablesServerSide#29]
Hi Rahman, I want to find out if the grid can support advanced searches outside the grid

**Comment by fingers10** [comment]
Hi @BernardBoakye,

Yes it is possible with a work around. Here are the steps,

**1. HTML:**
Add a external textbox with button,

```html
<div class="input-group mb-3">
    <input type="text" id="txtExternalSearch" class="form-control" placeholder="External Search" aria-label="External Search" aria-describedby="btnExternalSearch">
    <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="button" id="btnExternalSearch">Search</button>
    </div>
</div>
<jquery-datatables id="fingers10"
```

**2. JavaScript:**
in your external search button click, call the below script
```js
$('#btnExternalSearch').click(function () {
    table.column('0:visible').search($('#txtExternalSearch').val()).draw();
});
```

**3. Output:**
![image](https://user-images.githubusercontent.com/43729469/71542136-b2c88c00-2988-11ea-99af-05eb580a0ff3.png)

Check out the [demo](https://github.com/fingers10/JqueryDataTablesServerSideDemo) for working example

you can expand this further to your needs. Hope this answers your query.

if you need more control then you can use `additionalValues` in ajax configuration in jquery datatables and pass your values like shown below:
```js
data: function (data) {
   let additionalValues = [];
   additionalValues[0] = "Additional Parameters 1";
   additionalValues[1] = "Additional Parameters 2";
   data.AdditionalValues = additionalValues;

   return JSON.stringify(data);
}
```
and in the server side construct the columns parameter as shown below:
```c#
if (!string.IsNullOrWhiteSpace(param.AdditionalValues.Last()))
{
    var dtColumn = new DTColumn
    {
        Name = "co", // search operator
        Data = "Name", // column name
        Search = new DTSearch
        {
            Value = param.AdditionalValues.Last() // external search value
        },
        Orderable = true,
        Searchable = true
   };

   param.Columns[1] = dtColumn;
}

HttpContext.Session.SetString(nameof(JqueryDataTablesParameters), JsonSerializer.Serialize(param));
var results = await _demoService.GetDataAsync(param);
```

>**Give a star if you like this library.**

Thanks,
Abdul Rahman

**Comment by fingers10** [comment]
Hi @BernardBoakye,

I'm closing this as there isn't any response from your side. I believe above steps will resolve your query. Feel free to comment if you still not able to make it happen.

Cheers,
@fingers10

**Comment by leijae** [comment]
How would one utilize the default filter parameter for the DataTable instead of the first visible column?

That is to say something like this:

```
       $('#txtExternalSearch').on('keyup', function() {
                var text = $('#txtExternalSearch').val();
                table.column('0:visible').search(text).draw();
            });
```

 in place of this:

![image](https://user-images.githubusercontent.com/50371033/76795993-7d1d8d00-6798-11ea-8714-920f83336df5.png)

**Comment by leijae** [comment]
once again... nvm i solved it with 

table.search(text).draw();
