### ISSUE TITLE
adding html types of column search controls

### ISSUE THREAD

**Issue by UseMuse** [fingers10/JqueryDataTablesServerSide#30]
## I offer the following types:

1. input type date or datetime-local
2. input type number
3. input type string
4. select
5. multiple select

**Comment by fingers10** [comment]
Hi @UseMuse,

Thanks for reaching out. What do you mean by offer? Can you please explain more? You need the above input types in search inputs?

Thanks,
fingers10

**Comment by UseMuse** [comment]
under each column add the ability to indicate what type the search control should be:
**I offer the following types:**

1. input type date or datetime-local
2. input type number
3. input type string
4. select
5. multiple select

>  You need the above input types in search inputs?

Yes, I think it would be convenient

**Comment by UseMuse** [comment]
**for the following types search columns:**

1. input type [date  ](https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/date) or [datetime-local](https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/datetime-local)

use html5 or since jquery is used use the jquery [daterangepicker](https://www.daterangepicker.com/) plugin

**for the following types search columns:**

3. select
4. multiple select

use lazy loading or take data from the resulting data set

**Comment by UseMuse** [comment]
@fingers10 I’m interested, maybe I’ll try to implement it myself, but it’s not accurate :)But I do not have to wait)

**Comment by fingers10** [comment]
@UseMuse **I can look on adding html5 input types like number, text, datetime, datetime-local, select, etc.** But adding **jquery daterangepicker plugin** is completely out of scope for this package. This is just a server side processor. What you can do instead is **try to initialize the date picker on the inputs after the table has been initialized using the [initComplete](https://datatables.net/reference/option/initComplete)**
