### ISSUE TITLE
Add the ability to upload full data for excel

### ISSUE THREAD

**Issue by UseMuse** [fingers10/JqueryDataTablesServerSide#31]
Add the ability to upload full data for excel. Excluding pagination. 

I propose to implement this with a separate button "Export all to Excel". 
When you click on this button, the Length field of the JqueryDataTablesParameters class is set to -1. This would be tantamount to if we chose "Show all entries" - then, as the developers of [datables](https://datatables.net/) intended, an [example](https://datatables.net/examples/advanced_init/length_menu.html). But I suggest adding the ability to upload all the data without displaying them.

**Comment by UseMuse** [comment]
@fingers10 I’m interested, maybe I’ll try to implement it myself, but it’s not accurate :) But I do not have to wait)

**Comment by fingers10** [comment]
@UseMuse This piece of functionality has nothing to do with the server side processing package. I have updated the demo project for this **ALL** option with excel export. Please check [JqueryDataTablesServerSideDemo](https://github.com/fingers10/JqueryDataTablesServerSideDemo) project
