### ISSUE TITLE
Allow for Natural Sort

### ISSUE THREAD

**Issue by axelgunn** [fingers10/JqueryDataTablesServerSide#33]
**A suggested enhancement to sorting.**
Have you thought about a way to enable natural sorting? Could this potentially be done through the "SortOptionsProcessor"?

**Example 1**
-- this will return result that we DO NOT want 
select a from (values ('10.abc'), ('2.abc')) T(a) order by a asc; 
  
-- but the following will return the result EXPECTED 
select a from (values ('0010.abc'), ('0002.abc')) T(a) order by a asc; 

**Example 2**
``SELECT *
FROM #varchar_field
ORDER BY
CASE
WHEN ISNUMERIC(mixed_field) = 1 THEN CAST(mixed_field AS FLOAT)
WHEN ISNUMERIC(LEFT(mixed_field,1)) = 0 THEN ASCII(LEFT(LOWER(mixed_field),1))
ELSE 2147483647
END``

Otherwise, thanks for a great package.

**Comment by fingers10** [comment]
Please can you explain more about what you mean with natural sorting? Can you share your data models? How your datatable model looks like?

**Comment by fingers10** [comment]
Closing this as there is no response. Feel free to reopen if required.
