### ISSUE TITLE
SearchOption for ViewModel with combined fields

### ISSUE THREAD

**Issue by axelgunn** [fingers10/JqueryDataTablesServerSide#34]
Hi,

I cant find out how I am supposed to deal with the below scenario.

**I am mapping a datamodel to a viewmodel like this:**
`            CreateMap<DataModel, MyViewModel>()
                .ForMember(m => m.YearSeason, map => map.MapFrom(u => $"{u.Year}-{u.Season}"))
                .ReverseMap();`

**And adding searchoptions like this:**
query = SearchOptionsProcessor<MyViewModel, DataModel>.Apply(query, parameters.Columns);

**Resulting in this error that I understand but how do I deal with an issue like this?**
> Instance property 'YearSeason' is not defined for type 'Models.DataModel'
Parameter name: propertyName

Thanks in advance
Axel G

**Comment by fingers10** [comment]
Please share your data model and view model. On the other side add a star to the repo if this is helpful.

**Comment by axelgunn** [comment]
> public class DataModel
{
   public int Year { get; set; }
   public int Season { get; set; }
   public string GroupStrID { get; set; }
}

> public class ViewModel
{
   public string YearSeason { get; set; }
   public string GroupStrID { get; set; }
}

**AutoMapper**

> CreateMap<DataModel, ViewModel>()
    .ForMember(m => m.YearSeason, map => map.MapFrom(u => $"{u.Year}-{u.Season}"))
    .ReverseMap()

**Comment by fingers10** [comment]
If Year and Season are string fields in your database. Then you can implement something similar to FirstName and LastName as shown in demo project. Currently there is no support for combined integer fields.
