### ISSUE TITLE
[QUESTION] How do I use Language => Search as my primary search filter option?

### ISSUE THREAD

**Issue by leijae** [fingers10/JqueryDataTablesServerSide#35]
I'm don't want to have a search for each field. How do I use the Language => Search __INPUT__ as my primary mode of searching through column data? 

When I debug, clearly data is passed through the parameters, however no data is binded to the return model.

**Comment by fingers10** [comment]
Please can you share your view model and domain model? Can you explain more on what do you mean by language search?

**Comment by leijae** [comment]
Yea sorry that was vague...

![image](https://user-images.githubusercontent.com/50371033/76170602-70be8200-6151-11ea-8ac3-0ecbf0d3cf21.png)

![image](https://user-images.githubusercontent.com/50371033/76170607-88960600-6151-11ea-8a2c-ed6c15b63d11.png)

ViewModel
![image](https://user-images.githubusercontent.com/50371033/76170643-f3dfd800-6151-11ea-92f6-4422e671309d.png)

Entity
![image](https://user-images.githubusercontent.com/50371033/76170667-15d95a80-6152-11ea-9747-9a632fc9e0f7.png)

I suppose the issue I'm having that when I debug, data IS correctly passed from the search input to parameters. But if I search for any data within FirstName, LastName, or Phone the response is : "No matching records found" 

This value is always in Parameters.Search.Value as a string value, but it seems to be in the 'Language' property of the DataTable

Thanks for the quick response!

**Comment by leijae** [comment]
Ok, there is probably a more correct way of doing this... but I just added 

`            if (!string.IsNullOrWhiteSpace(table.Search.Value))
            {
                query = query.Where(x => x.LastName.Contains(table.Search.Value) || x.FirstName.Contains(table.Search.Value));
            }
`

and now I get desired results.
