### ISSUE TITLE
[FEATURE] General CSV export instead of Excel

### ISSUE THREAD

**Issue by leijae** [fingers10/JqueryDataTablesServerSide#36]
There was a slight learning curve, but once I understood it; it's a fantastic tool that I'm going to keep coming back to. I'd like to send you  some BAT (it's the only crypto I have PM me for details).

I have a request to export as a general .csv instead of excel.

**Comment by fingers10** [comment]
Dear Leijae,

Sound good. Thanks for your kind words. I'll work on this and push it in the next release. 

What is BAT?

Thanks,
fingers10

**Comment by leijae** [comment]
It's a crypto currency for users of Brave Browser. It shows up by each users name
![image](https://user-images.githubusercontent.com/50371033/76795603-9e31ae00-6797-11ea-9761-049b4373c991.png)
(Red and White triangle in above image)


If you register as a content creator I can send you some :)

![image](https://user-images.githubusercontent.com/50371033/76795653-bb667c80-6797-11ea-9cdb-8e2d9d6a8546.png)

**Comment by fingers10** [comment]
I would be happy if you could sponsor/support/donate for this project via my paypal account.

**Comment by leijae** [comment]
Sure! Do you have a platform other than PayPal that I can send money to?
Maybe Venmo?

**Comment by fingers10** [comment]
Are you into Google Pay?

**Comment by leijae** [comment]
Yes. What email shall I use?

**Comment by fingers10** [comment]
Can you share me your Google pay email or ID or Phone Number? I'll ping you in GPay

**Comment by leijae** [comment]
leijae@gmail.com
