### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kyziur** [fingers10/JqueryDataTablesServerSide#37]
**Describe the bug**
Problem with expression that is created when trying to search with properties that are type of enum. Ef core 3.0 does allow only for evaluating queries on one side - server side (app side) or database side. Query that i am receiving from example app you have provided after adding sql provider is:
```value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[AspNetCoreServerSide.Models.DemoEntity]).AsNoTracking().Include(x => x.DemoNestedLevelOne).ThenInclude(y => y.DemoNestedLevelTwo).Where(DemoEntitySearch => (True AndAlso DemoEntitySearch.Position.ToString().Equals(Accountant.ToString(), OrdinalIgnoreCase)))```
I think that the problem is with `ToString().Equals(Accountant.ToString() ` - it cannot be evaluated on database side which means that all the stuff has to be loaded to memory before we can filter which can lead to performance issues. 

**To Reproduce**
Instead of using in memory provider as database use sql server or any other provider that is connecting to real database. Then try to filter table on enum type.

**Expected behavior**
Properly translated query for enum types so there won't be any drawback using this plugin.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by fingers10** [comment]
Thanks for figuring out. I'll inspect this and get back.

**Comment by fingers10** [comment]
Were you able to run this against database properly? I'm getting run time error while running against database. The expression fails to build for me. How about you? You're facing the same issue or you were able to execute the query?

**Comment by fingers10** [comment]
Figured out. Will fix this in the upcoming release.

**Comment by fingers10** [comment]
pushed fix to master branch. please check in the upcoming release.
