### ISSUE TITLE
[QUESTION] How does one style the "Length Menu?

### ISSUE THREAD

**Issue by leijae** [fingers10/JqueryDataTablesServerSide#39]
How could I style the length menu? I was searching your demo and didn't see an example of this.

![image](https://user-images.githubusercontent.com/50371033/78462391-17d20300-7697-11ea-85db-f57cf928bff7.png)

**Comment by fingers10** [comment]
try to target `.dataTables_length select`. Better ask in `stackoverflow` for immediate answers.
