### ISSUE TITLE
GetDataAsync Take Start for paging

### ISSUE THREAD

**Issue by s004183** [fingers10/JqueryDataTablesServerSide#4]
First launch Skip fails. Is negative number. 
table.Start value is Zero for first page / resultset. (Zero -1)  is negative number. 
var items = await query
                .AsNoTracking()
                .Skip(table.Start - 1 * table.Length)
                .Take(table.Length)
                .ProjectTo<Demo>(_mappingConfiguration)
                .ToArrayAsync();
return items;

**Comment by fingers10** [comment]
Hey @s004183 ,

Can you share you client side Jquery DataTables configuration? This could help me to analyze further.

Cheers,
Abdul :)

**Comment by s004183** [comment]
Can I offer a connection to my computer via and access directly to my dev.
computer. See my other mail after this.

**Comment by s004183** [comment]
Hello Abdul and nice to hear you!

For test Project: I test your demo Project and still not work paging. I actívated button in DataTable <DOM: “BTIRF…”> I think, and your demo Project only shows one page. I change the number of rows to return to 5 and not more pages are shown…

 

More in deep test, I can offer you an Access to my develop machine via TeamViewer. I use VS2017, SQL Server (Remote machine).

I send you the app.js.

Don’t worry about machine connection, before your connection I will do an snapshot (is VM machine) to revert to initial state if you change something for test.

 

I send you two pictures: one with ten rows and with same filter one with 25 rows. There are a lot of rows but in any case shows more than one page the DataTable.

 

I don’t know how to facilitate the test, but I am very interested in how you implement DataTables: is very easy and very direct, just what I need.

 

Cheers! Paco Bevia.

 

PD: refering to negative number on initial getdataasync (my another issues post), I just put and IF to turn to Zero when the number to take is negative. My be an instrucción like ((x < 0) ? 0:x) is more elegant.

 

        public async Task<StudyList[]> GetDataAsync(DTParameters table)
        {
            IQueryable<StudyListEntity> query = _context.StudyList;
            query = new SearchOptionsProcessor<StudyList,StudyListEntity>().Apply(query,table.Columns);
            query = new SortOptionsProcessor<StudyList, StudyListEntity>().Apply(query,table);
            var skip_calc = (table.Start - 1 * table.Length);
            if (skip_calc < 0) skip_calc = 0;
            var items = await query
                .AsNoTracking()
                .Skip(skip_calc)
                .Take(table.Length)
                .ProjectTo<StudyList>(_mappingConfiguration)
                .ToArrayAsync();
            return items;
        }

 

PD2:

In my case I need the first filter to be Range Time. I use a View in SQL that is my entity… ReadOnly.

 

 

De: Abdul Rahman [mailto:notifications@github.com] 
Enviado el: viernes, 5 de abril de 2019 12:43
Para: fingers10/JqueryDataTablesServerSide
CC: s004183; Mention
Asunto: Re: [fingers10/JqueryDataTablesServerSide] GetDataAsync Take Start for paging (#4)

 

Hey @s004183 <https://github.com/s004183>  ,

Can you share you client side Jquery DataTables configuration? This could help me to analyze further.

Cheers,
Abdul :)

**Comment by fingers10** [comment]
Hey @s004183 ,

Here is a quick fix,

1. Add a PagedResults{T}.cs model,
```
public class PagedResults<T>
    {
        public IEnumerable<T> Items { get; set; }

        public int TotalSize { get; set; }
    }
```

2. Change data access code to,
```
public async Task<PagedResults<Demo>> GetDataAsync(DTParameters table)
        {
            IQueryable<DemoEntity> query = _context.Demos;
            query = new SearchOptionsProcessor<Demo,DemoEntity>().Apply(query,table.Columns);
            query = new SortOptionsProcessor<Demo,DemoEntity>().Apply(query,table);

            var size = await query.CountAsync();

            var items = await query
                .AsNoTracking()
                .Skip((table.Start / table.Length) * table.Length)
                .Take(table.Length)
                .ProjectTo<Demo>(_mappingConfiguration)
                .ToArrayAsync();

            return new PagedResults<Demo>
            {
                Items = items,
                TotalSize = size
            };
        }
```

3. Change controller code to,
```
[HttpPost]
        public async Task<IActionResult> LoadTable([FromBody]DTParameters param)
        {
            try
            {
                var results = await _demoService.GetDataAsync(param);

                return new JsonResult(new DTResult<Demo> {
                    draw = param.Draw,
                    data = results.Items,
                    recordsFiltered = results.TotalSize,
                    recordsTotal = results.TotalSize
                });
            } catch(Exception e)
            {
                Console.Write(e.Message);
                return new JsonResult(new { error = "Internal Server Error" });
            }
        }
```

4. Try you own page length in your js,
```
lengthMenu: [5, 10, 15, 20],
            //dom: '<tr>',
```

I'll update my demo solution and code soon. Hope this fixes your problem.

Thanks,
Abdul

**Comment by s004183** [comment]
Hi Abdul,
    Your update solves the issue. ;)
Thanks!
