### ISSUE TITLE
Date Range Filter

### ISSUE THREAD

**Issue by vbharuwa** [fingers10/JqueryDataTablesServerSide#40]
Can we get date range filter facility on date column?

**Comment by fingers10** [comment]
Hey @vbharuwa ,

You can enter the date range in the column search text box like `16/04/2020 - 20/04/2020` and in the server side you can add a little bit of logic to handle this as follows,

**JS Configuration:**
```js
columns:
[
    {
         data: "DateRangeColumn",
         name: "gte"
    },
...
]
```

**Action Method:**

```c#
if (!string.IsNullOrWhiteSpace(param.Columns[daterangecolumnindex]))
{
    var dtColumn = new DTColumn
    {
        Name = "lte", // search operator
        Data = "DateColumnName", // column name
        Search = new DTSearch
        {
            Value = param.Columns[daterangecolumnindex].Search.Value.Split('-')[1] // to date value
        },
        Orderable = true,
        Searchable = true
   };

   params.Columns[daterangecolumnindex].Search.Value = param.Columns[daterangecolumnindex].Search.Value.Split('-')[0]

   // Add dtColumn to params.Columns array;
}
```

Now this should generate expression like `_context.Entity.Where(x => x.Date >= '16/04/2020' && x.Date <= '20/04/2020' )`.

Hope this helps.

KR,
@fingers10

**Comment by fingers10** [comment]
Closing this as there is no response.
