### ISSUE TITLE
[QUESTION] How to make search working API side with different Entity model.

### ISSUE THREAD

**Issue by ElChepos** [fingers10/JqueryDataTablesServerSide#42]
Hey @fingers10,

today I was trying to implement the JqueryDataTablesPagedResults in my API and I ran into an issue. 

I have an API that return an object that contains more data that the viewModel that I use to display the table itself. It working good to display the data, but the search and sort won't work.

Example :

The call on the API side look like the example 
public async Task<JqueryDataTablesPagedResults<Response>> GetPage(JqueryDataTablesParameters tableParams, IQueryable<TEntity> query)
        {
            Response[] items = null;
            
            query = SearchOptionsProcessor<Response, TEntity>.Apply(query, tableParams.Columns);
            query = SortOptionsProcessor<Response, TEntity>.Apply(query, tableParams);
            
            var size = await query.CountAsync();

            if (tableParams.Length > 0)
            {
                items = await query
                .Skip((tableParams.Start / tableParams.Length) * tableParams.Length)
                .Take(tableParams.Length)
                .ProjectTo<Response>(_mappingConfiguration)
                .ToArrayAsync();
            }
            else
            {
                items = await query
                .ProjectTo<Response>(_mappingConfiguration)
                .ToArrayAsync();
            }

            return new JqueryDataTablesPagedResults<Response>
            {
                Items = items,
                TotalSize = size
            };
        }

TEntity is for example a class Employee with FirstName, LastName, Phone and Sexe, CreateDate, Modify By.
Response in a class EmployeeResponse with only FirstName, LastName, Phone and Sexe.

On the client side, the method 
 var results = await torosApiFacade.GetPageByPost<ViewModel>(url, param);
                    return new JsonResult(new JqueryDataTablesResult<ViewModel>
                    {
                        Draw = param.Draw,
                        Data = results.Items,
                        RecordsFiltered = results.TotalSize,
                        RecordsTotal = results.TotalSize
                    });

Where ViewModel is the EmployeeResponse class minus the Sexe with all the JqueryDataTable DataAnnotation.

I receive the data #1 and it working. But when I enter a value in any search column, it not working in the API side, I still receive all the data. I look like the SearchOptionsProcessor don't work since the EmployeeResponse is not exactly like the EemployeeViewModel.

If I create the EmployeeViewModel directly in my api and use it with SearchOptionsProcessor it working #1. Since the front end and the api model is the same. But in real case my API don't have and don't need to know my ViewModel. 

**Expected behavior**
Since my API can't have a model for each my Front End view I would expect it to work since my Entity have all the ViewModel data and more. Let me know if I do something wrong here.

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Chrome

**Additional context**
.Net Core 3.1 with latest Nuget JqueryDataTable version 4

Thx

**Comment by fingers10** [comment]
Can you directly make a call to your API from jQuery Data tables by changing the ajax url property in jQuery Data tables script?

Can you share your models? ViewModel, API Response Model, API Request Model?

**Comment by fingers10** [comment]
@jptoros Closing this as there is no response. Feel free to reopen if needed. Or post the solution which worked for you. That will help others.
