### ISSUE TITLE
Buttons at footer using jquery datatables

### ISSUE THREAD

**Issue by pankaj18sharma** [fingers10/JqueryDataTablesServerSide#45]
**Describe the question**
A clear and concise description of what the question is.
is it possible to get the buttons using jquery datatables near paging like-

![image](https://user-images.githubusercontent.com/62420783/82119312-f20e4280-979a-11ea-9795-648b4823ef4a.png)
Cancel and Ok Buttons...Help would be appreciated.

**Comment by fingers10** [comment]
What is the purpose of the button at the footer?

**Comment by pankaj18sharma** [comment]
Actually i'm using datatable on Modal Popup so cancel button will be used for dismissing the popup and Ok button is used for selecting the row and after clicking the ok will fetch it's data.

**Comment by fingers10** [comment]
In that case you have these button on the modal popup itself. This has nothing to do with Jquery DataTables

**Comment by pankaj18sharma** [comment]
Thanks for the quick response Abdul.
Yes i have done it through that...But i was thinking for the alternate using Jquery Datatables.

**Comment by fingers10** [comment]
This doesn't come under the jQuery Data tables scope. What you have done is correct.
