### ISSUE TITLE
Searching date is not working perfectly

### ISSUE THREAD

**Issue by pankaj18sharma** [fingers10/JqueryDataTablesServerSide#46]
i am searching date in format mm/dd/yyyy and in db the dates are in format like yyyy-mm-dd hh-mm-ss...but it's not working as excepted...Need Help stuck my work

Code ;-
 table.columns().every(function (index) {
      $('#test tr:last th:eq(' + index + ') input')
        .on('keyup change',
          function (e) {      
            table.column($(this).parent().index() + ':visible').search(this.value).draw();
          });
    });

**Comment by fingers10** [comment]
What is the type of date field in database? DateTime or Varchar?

**Comment by pankaj18sharma** [comment]
It's datetime2(7)

**Comment by fingers10** [comment]
Can you share your view model and entity model?

Please make sure to follow issues guidelines while posting any issue.

**Comment by pankaj18sharma** [comment]
Entity Model:-
```c#
public class ConfigureWarranty
    {
        public int Id { get; set; }
        public int ExtendedMonth { get; set; }
        public DateTime? CreatedOn { get; set; }
    }
```
ViewModel:-
```c#
public class ConfigureWarranty
    {
        [JqueryDataTableColumn(Order = 1)]
        public int Id { get; set; }

        [JqueryDataTableColumn(Order = 2)]
        [SearchableDateTime(EntityProperty = "CreatedOn")]
        public DateTime? CreatedOn { get; set; }

        [JqueryDataTableColumn(Order = 3)]
        public int ExtendedMonth { get; set; }
    }
```
It's not working as expected. Please Help

**Comment by fingers10** [comment]
You're using `eq` operator in date column right? Did you check the [Demo Solution](https://github.com/fingers10/JqueryDataTablesServerSideDemo)? Apply migration and check it against the database. It is also creating `datetime2(7)` column in database and it works fine.
