### ISSUE TITLE
Column search with complex objects support?

### ISSUE THREAD

**Issue by olek-su** [fingers10/JqueryDataTablesServerSide#5]
Hi,

I am trying to implement this extension in my project, but it seems that individual column search doesn't work with complex objects (at least in my case?).

I have an table 'Orders' in database. Order entity embraces fields like Id, Status, Customer.Firstname,  Customer.Lastname,  Customer.Email where the last three belong to class Customer which has One-To-Many relationship with Order entity. And while search by, for instance, Id works just fine, any attempt to sort/filter by some of last 3 columns fails at this part:
`query = new SearchOptionsProcessor<OrderObject, Order>().Apply(query, table.Columns);`

Is that actually not supported yet or it's just some problem with mapping on my side?

Thank you beforehand :)

**Comment by fingers10** [comment]
Dear olek-su,

This feature is currently not supported. I'll add this in my future release. Stay tuned for the updates.

Thanks,
Abdul

**Comment by fingers10** [comment]
added the feature in v2.2.0
