### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by olegbonder** [fingers10/JqueryDataTablesServerSide#52]
how can we use localization? Please show an example

**Comment by fingers10** [comment]
Hi olegbonder,

Thanks for reaching out. Please refer issue #16 

Thanks,
Abdul Rahman

**Comment by olegbonder** [comment]
Hi fingers10,
I refered to issue #16. But I dont't understand how to use constructor in class "JqueryDataTablesHtmlLocalizedTagHelper" using DI (dependecy injection)
My steps:
1. Startup.cs:
            `services.AddLocalization(opt => opt.ResourcesPath = "Resources");`
            `services.AddScoped<IDemoService, DefaultDemoService>();`
            `services.Configure<RequestLocalizationOptions>(options =>`
           ` {`
             `   var supportedCultures = new[]`
                `{`
                    `new CultureInfo("en"),`
                    `new CultureInfo("ru")`
                `};`
          `      options.DefaultRequestCulture = new RequestCulture("ru");`
           `     options.SupportedCultures = supportedCultures;`
           `     options.SupportedUICultures = supportedCultures;`
           ` });`
             `services.AddControllersWithViews()`
               ` .AddViewLocalization()`
               ` .AddDataAnnotationsLocalization()`

2. Add Resource Files for my Model "Demo" (Demo.en.resx and [Demo.ru.resx):
![issueLocalizationDataTable](https://user-images.githubusercontent.com/22918095/90181615-6e73ea00-ddb9-11ea-96aa-457b5e91b323.png)
Add Property "Name" in Resource Files
3. In Demo-model add attribute:
        `[Display(Name = "Name")]`
        `[SearchableString(EntityProperty = "FirstName,LastName")]`
        `[Sortable(EntityProperty = "FirstName,LastName", Default = true)]`
        `public string Name { get; set; }`
3. Add in _ViewImports.cshtml:
`@inject IHtmlLocalizer<JqueryDataTablesTagHelper> sl`
4. In View replace tag-helper "jquery-datatables" on "jquery-datatables-html-localized"

No effect
How can i localize table columns using DataAnnotationsLocalization in view-model properties?
Thanks

**Comment by fingers10** [comment]
Did you try [JqueryDataTablesHtmlLocalizedTagHelper](https://github.com/fingers10/JqueryDataTablesServerSide/blob/master/AspNetCoreWeb/TagHelpers/JqueryDataTablesHtmlLocalizedTagHelper.cs).

Refer [Table HTML](https://github.com/fingers10/JqueryDataTablesServerSide#table-html) section in Docs.
>Please note: If you prefer HTML Localization then, <jquery-datatables-html-localized> Tag Helper is available with all the above properties.

**Comment by olegbonder** [comment]
Yes, I did, but no effect.

вс, 16 авг. 2020 г., 7:01 Abdul Rahman <notifications@github.com>:

**Comment by olegbonder** [comment]
Can you add test project where use localization in columns?

Thanks

**Comment by fingers10** [comment]
[Demo Project](https://github.com/fingers10/JqueryDataTablesServerSideDemo) now supports localization.
