### ISSUE TITLE
Enhancement in SortOptionsProcessor

### ISSUE THREAD

**Issue by KhalilMohammad** [fingers10/JqueryDataTablesServerSide#6]
95% of time,we need sort operations over different entities in different tables.

Current SortOptionsProcessor's biggest limitation in my opinion is sort can only be applied to single entity.

Example api
new SortOptionsProcessor<DemoModel>().Apply(query,table);

DemoModel is the final select/projection of query.

I was thinking you could add overload to SortOptionsProcessor. Also I could submit PR for this ,If I have some free time available.

**Comment by fingers10** [comment]
Dear KhalilMohammad,

Thanks for your support. I planning to implement complex search and sort in future release. Feel free to submit a PR. I'll review and add it the next release,

Cheers,
Abdul

**Comment by fingers10** [comment]
Dear KhalilMohammad,

Did you get a chance to look at this any further?

Thanks,
Abdul

**Comment by KhalilMohammad** [comment]
I did not find time, I am doing 2 jobs currently 40 - 60 hours per week.

**Comment by fingers10** [comment]
added the feature in v2.2.0
