### ISSUE TITLE
[QUESTION] How use IncludeInReport on Dictionary

### ISSUE THREAD

**Issue by jjjhong91** [fingers10/JqueryDataTablesServerSide#65]
Hi

I implement  to export csv from mongodb, and I have property that is Dictionary<string,string>.
There are not working by using [IncludeInReport] and [NestedInReport].

How can I do?

**Comment by fingers10** [comment]
@jjjhong91 `IncludeInReport` can be used only on primitive types. I suppose you are using this on your domain model? If so you can transform your Dictionary in domain modal to a separate model for reporting and use primitive types in that and decorate with report attributes.

**Comment by jjjhong91** [comment]
@fingers10 I also think it.
thank you!
