### ISSUE TITLE
Nullable search

### ISSUE THREAD

**Issue by gaugo123** [fingers10/JqueryDataTablesServerSide#7]
Hi,
Thanks for your great job! really usefull
when working with Nullable properties makes it impossible to filter on the nullable property.

ps: I've tried to clone it and fix the issue but could not use it as I do not find all objects (i.e. DTParameters)

**Comment by fingers10** [comment]
Hi gaugo,

Happy to see you enjoying this nuget package.

Thanks for figuring out the issue. I working on v2 release and will be releasing it in couple of days. V2 has some breaking changes. I have standardized and renamed the `DTParameters` to `JqueryDataTablesParameters` in the V2.

Feel free to submit a PR with your changes I'll review and include them in next release. 😄

Cheers,
Abdul

**Comment by gaugo123** [comment]
Abdul,
thanks for the reply and the work.
I've figured out all the changes yesterdsay when cloning the repo.
I'll work on the issue and will definitivly let you now

**Comment by gaugo123** [comment]
Abdul,
I just pushed a new update. 
Unfortunately, I did not do it based on the last comit but only on the current Nuget version.
mods are super simple so feel free to either cherry pick some changes or incorporate onto your new feature....
cheers,
gaugo

**Comment by fingers10** [comment]
Hey gaugo123,

Thanks for the update. I'm new to git. Where can I find the update? Submitted a PR?

Cheers,
Abdul

**Comment by gaugo123** [comment]
oups, I did not doubled checked... I get a 403...
I'm also new into git.... 
I'll try to adapt my project to the lattest Version and provide you the changes...
would be nice of you to tell me what commit is from the lattest nuget package

**Comment by gaugo123** [comment]
PR Submitted,
hope you'll like it...
Just let me know

**Comment by fingers10** [comment]
Hi gaugo123,

This is the latest commit `809b4a1` in `master` branch. I'll review and test your PR and get back to you.

Cheers,
Abdul

**Comment by fingers10** [comment]
Hi gaugo123,

Merger your PR #8 and published v2.1.0. Thanks for spotting the issue and helping with PR. @gaugo123  💯
